-- drop database StudyHub;
-- create database StudyHub;
use StudyHub;
select * from user;
-- INSERT INTO  personal_dictionary (id_pd, user_id_user) VALUES (1, 1);
-- INSERT INTO  user (id_user, email, name, password, personal_dictionary_id_pd) VALUES (1, 'alibil@gmail.com', 'alibil', 'user1password', 1);
-- INSERT INTO  admin (id_admin, email, name, password) VALUES (1, 'alibil@gmail.com', 'alibil', 'user1password');
-- INSERT INTO text (name,id_text,id_admin, complexity_level, content) VALUES ('The Mona Lisa', 1,1, 'Advanced', 'The Mona Lisa is one of the most famous and iconic paintings in the world, created by the Italian artist Leonardo da Vinci. Though I cannot see the picture, I can certainly describe it to you.
-- The Mona Lisa depicts a half-length portrait of a woman believed to be Lisa Gherardini, an Italian noblewoman. She is shown sitting against a dark background with a vast landscape visible behind her. The woman is portrayed in a three-quarter view, facing slightly to the left.
-- One of the most captivating aspects of the painting is the enigmatic smile on Mona Lisa\'s face. It is subtle and mysterious, adding an air of intrigue and fascination to the artwork. Her eyes, framed by delicately arched eyebrows, seem to gaze directly at the viewer with a sense of warmth and curiosity.
-- Mona Lisa\'s appearance is remarkable for its meticulous attention to detail. Leonardo da Vinci employed a technique known as sfumato, using thin layers of paint and subtle blending to create soft transitions between colors and tones. This technique gives the painting a sense of depth and a realistic, almost ethereal quality.
-- She is depicted wearing a traditional Florentine gown, with her hands folded in front of her. The composition is balanced and harmonious, with the subject centered in the frame. The use of light and shadow adds depth to her features, highlighting the contours of her face and creating a lifelike effect.
-- The Mona Lisa\'s enduring appeal lies not only in its technical brilliance but also in the sense of mystery that surrounds it.');
--  INSERT INTO text (name,id_text,id_admin, complexity_level, content) VALUES ('The Impact of Technology on Society', 3,1, 'Advanced', 'The impact of technology on society is a vast and complex topic that has been studied and debated for many years. Advances in technology have brought about many positive changes in society, from improved medical treatments to more efficient transportation and communication systems. However, there are also concerns about the negative effects of technology on society, such as the potential for increased social isolation, loss of jobs due to automation, and privacy concerns. As technology continues to advance at a rapid pace, it is important for individuals and society as a whole to consider the implications and make informed decisions about its use.');
-- INSERT INTO text (name,id_text,id_admin, complexity_level, content) VALUES ('Rest', 2,1, 'Intermediate', 'Rest is a vital aspect of our lives, encompassing both physical and mental rejuvenation. It is a state of tranquility and relaxation that allows our bodies and minds to recover from the demands and stresses of daily life. While I cannot directly perceive or experience rest as a machine, I can provide you with insights and descriptions related to the concept.
-- Rest can take many forms, ranging from a peaceful nap or a good night\'s sleep to moments of leisure, solitude, or meditation. It provides an opportunity to recharge our energy, restore our focus, and replenish our emotional well-being. During restful periods, our bodies repair themselves, our minds consolidate memories, and our creativity often flourishes.
-- Physical rest often involves finding comfort and relief by lying down, reclining in a cozy chair, or simply taking a break from physically demanding activities. It allows our muscles to relax, our breathing to slow down, and our heartbeat to stabilize. The gentle rhythm of rest can be therapeutic, soothing both our bodies and our minds.
-- Mental rest, on the other hand, involves freeing ourselves from the constant influx of information and mental stimulation. It means finding moments of stillness amidst the chaos of our thoughts. Engaging in activities such as meditation, mindfulness, or simply disconnecting from technology can help quiet our minds and bring a sense of calm and clarity.
-- Rest is not solely about inactivity; it also encompasses engaging in activities that bring us joy, contentment, and a sense of fulfillment. It can involve pursuing hobbies, spending quality time with loved ones, reading a book, listening to music, or simply being in nature. These moments of leisure and recreation allow us to rejuvenate our spirits and find balance in our lives.
-- In a fast-paced and demanding world, rest is often undervalued or overlooked. However, recognizing the importance of rest and intentionally incorporating it into our routines can have profound effects on our overall well-being. It enhances our productivity, improves our focus, and nurtures our mental and emotional health.
-- So, whether it\'s a peaceful night\'s sleep, a moment of solitude, or engaging in activities that bring you joy, embrace the concept of rest and make it a priority in your life. By doing so, you can find renewed energy, clarity, and a greater sense of harmony in your daily endeavors.');
-- INSERT INTO text (name,id_text,id_admin, complexity_level, content) VALUES ('Winter', 4,1, 'Advanced', 'Winter is a season that captivates the senses with its enchanting frost-kissed landscapes and crisp, chilly air. As nature\'s brushstrokes paint the world in hues of white, a serene tranquility descends upon the surroundings. Delicate snowflakes dance from the heavens, gracefully adorning everything they touch.
-- The winter season invites cozy moments by the crackling fireplace, where families gather to share laughter, stories, and warmth. It\'s a time for steaming mugs of hot cocoa, warming hands and hearts simultaneously. Frosty mornings greet us with a gentle embrace, inviting us to explore a world transformed into a glistening wonderland.
-- Nature itself seems to hibernate during winter, as trees stand bare and dormant, patiently awaiting the arrival of spring. Yet, amidst the stillness, a hidden symphony arises. The crunch of boots upon freshly fallen snow, the distant laughter of children building snowmen, and the melodious chirping of birds that decided to brave the cold, all compose a serene winter melody.
-- Adventurous spirits find delight in winter sports and activities. The exhilaration of gliding down snow-covered slopes on skis or snowboards, or the simple joy of ice skating on frozen ponds, create unforgettable memories and embrace the spirit of the season. And when the night sky unfolds its magnificent tapestry of stars, shimmering against the cold, clear backdrop, the magic of winter reaches its peak.');
-- INSERT INTO text (name,id_text,id_admin, complexity_level, content) VALUES ('Love', 7,1, 'Beginner', 'Love is a force that transcends boundaries, defies logic, and fills our lives with profound meaning. It is an exquisite tapestry woven with threads of tenderness, passion, and compassion, captivating the hearts of both the young and the old. Love, in all its myriad forms, has the power to transform us, heal us, and make us whole.

-- At its core, love is an inexplicable connection that binds us to one another. It is a dance of souls, where two individuals intertwine their lives, creating a beautiful symphony of emotions. Love blossoms in the smallest gestures—a gentle touch, a shared smile, or a knowing glance. It thrives in the moments of vulnerability, where we open our hearts and let another person in.

-- Love is not without its challenges. It navigates through storms of disagreements and trials, testing the strength of the bond we share. Yet, it is in overcoming these obstacles that love shines even brighter. It teaches us patience, forgiveness, and the art of compromise. Love is not a fairytale; it is a journey that requires dedication and effort, but the rewards it bestows are immeasurable.

-- Love is not confined to romantic relationships alone; it extends to the love we have for our families, our friends, and our communities. It is the unconditional support of a parent, the unwavering loyalty of a friend, and the selfless acts of kindness we extend to strangers. Love has the power to bridge divides, dissolve differences, and bring people together in harmony.

-- In the realm of love, vulnerability is a strength, not a weakness. It is the willingness to expose our deepest fears, desires, and flaws, trusting that the other person will accept us wholly. Love encourages growth and self-discovery, for it is through love that we see ourselves reflected in the eyes of our loved ones, enabling us to become the best version of ourselves.

-- Love is a complex tapestry of emotions. It can be gentle and serene like a calm sea, or fierce and wild like a raging storm. It can evoke immense joy and euphoria, but it can also bring moments of heartache and sorrow. Love is not always easy, but it is always worth it.');
-- INSERT INTO text (name,id_text,id_admin, complexity_level, content) VALUES ('Embracing the Sun: A Summer Affair', 6,1, 'Advanced', 'As the days lengthen and the warmth of the sun caresses our skin, we find ourselves immersed in the enchanting season of summer. It is a time of vibrant energy, where nature flourishes in all its glory and the world seems to come alive. Welcome to a realm where laughter echoes through the air, where time slows down, and where memories are etched in golden hues.

-- Summer invites us to embark on a sensory adventure, tantalizing our taste buds with juicy fruits and refreshing treats. It beckons us to bask in the gentle embrace of a gentle breeze, as the symphony of chirping birds and rustling leaves serenades our ears. It awakens our senses with the fragrance of blooming flowers and the earthy aroma of freshly cut grass.

-- This season is an invitation to surrender to the joy of simple pleasures. Feel the soft grains of sand slip between your toes as you walk along the sun-kissed shore. Dive into the cerulean depths of the ocean, where the waves embrace you like an old friend, and the world below reveals a kaleidoscope of vibrant marine life. Build castles in the sand, letting your creativity run wild, and relish in the laughter that bubbles up from within.

-- Summer is a time of adventure, where exploration knows no bounds. Take a road trip to uncharted destinations, where hidden gems await your discovery. Lose yourself in the embrace of lush forests, where sunlight filters through the dense canopy, casting an ethereal glow on your path. Seek solace in the majestic mountains, their peaks reaching towards the heavens, offering panoramic vistas that take your breath away.

-- But summer is not only about external exploration; it is also an invitation to journey within. Find solace in the quiet moments, where the world fades away and your thoughts drift like lazy clouds across a clear sky. Engage in soulful conversations under a starlit sky, where friendships deepen and connections strengthen. Let the warmth of the season infuse your spirit with renewed inspiration and the courage to chase your dreams.');
